additionalHeaders = ["scripts/builder-header-style.toml"]

headerPath = "scripts/license-header.txt"

includes = [
    "Makefile",
    "*.Makefile",
    "*.go",
    "*.sh",
]

excludes = [
    "vendor",
    "*.pb.go",
]

[git]
attrs = 'enable'
ignore = 'enable'

[properties]
copyrightOwner = "Apple Inc. and the container-builder-shim project authors"

[mapping.GO_STYLE]
extensions = ["go"]
